server:
  port: 8082
  
# Configuration for MySQL Database
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3307/my_schema
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver